services:
  postgres:
    image: postgres:15
    container_name: ${PACKAGE_NAME}_db
    profiles:
      - dev
      - prod
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tomerblackburn-backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: softvence/${PACKAGE_NAME}:latest
    profiles:
      - prod
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PACKAGE_NAME}_app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - SMTP_FROM=${SMTP_FROM}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tomerblackburn-backend-network
    command: sh -c "echo 'Checking Prisma setup...' && ls -la prisma/ && ls -la prisma/migrations/ && echo 'Running migrations...' && npx prisma migrate deploy && echo 'Starting application...' && node dist/src/main"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PACKAGE_NAME}_phpmyadmin
    profiles:
      - prod
      - dev
    restart: always
    environment:
      PMA_HOST: postgres
      PMA_PORT: 5432
      PMA_USER: ${POSTGRES_USER}
      PMA_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - postgres
    networks:
      - tomerblackburn-backend-network
networks:
  tomerblackburn-backend-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
